[project]
name = "webrviz"
version = "0.1.0"
description = "CLI-based Web Application Mapper for Security Researchers"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "rich>=13.7"
]

[project.scripts]
webrviz = "webrviz.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["webrviz*"]
